// Package module is the protoc-gen-nexgen PG* module. Execute runs the
// pipeline in DESIGN.md §3: options, mapping, filter, closure, naming,
// assembly, and emit.
package module

import (
	"fmt"
	"path"
	"sort"
	"strings"

	pgs "github.com/lyft/protoc-gen-star/v2"

	"github.com/temporalio/cloud-api/tools/nexgen/filter"
	"github.com/temporalio/cloud-api/tools/nexgen/internal/closure"
	"github.com/temporalio/cloud-api/tools/nexgen/internal/emit"
	"github.com/temporalio/cloud-api/tools/nexgen/internal/mapping"
	"github.com/temporalio/cloud-api/tools/nexgen/internal/naming"
	"github.com/temporalio/cloud-api/tools/nexgen/internal/schema"
)

const (
	schemaURI       = "https://json-schema.org/draft/2020-12/schema"
	nexusrpcVersion = "1.0.0"
	generatedHeader = "Code generated by protoc-gen-nexgen. DO NOT EDIT."
)

// Module generates nexgen definition files.
type Module struct {
	*pgs.ModuleBase
}

// New returns the module.
func New() *Module { return &Module{ModuleBase: &pgs.ModuleBase{}} }

// Name implements pgs.Module.
func (m *Module) Name() string { return "nexgen" }

type options struct {
	services []string // empty means every service in the files to generate
	format   emit.Format
	filter   *filter.Filter
}

func parseOptions(p pgs.Parameters) (options, error) {
	var o options
	for k := range p {
		switch k {
		case "", "services", "out_format", "filter", "output_path":
		default:
			return o, fmt.Errorf("unknown option %q; supported options are services, out_format, and filter", k)
		}
	}
	if s := p.Str("services"); s != "" {
		// PG* splits the parameter string on commas, so names use +.
		o.services = strings.Split(s, "+")
	}
	var err error
	if o.format, err = emit.ParseFormat(p.Str("out_format")); err != nil {
		return o, err
	}
	if path := p.Str("filter"); path != "" {
		if o.filter, err = filter.Load(path); err != nil {
			return o, err
		}
	}
	return o, nil
}

// Execute implements pgs.Module. Every problem is reported through the
// response's error field, so protoc and buf print it and no files are written.
func (m *Module) Execute(targets map[string]pgs.File, pkgs map[string]pgs.Package) []pgs.Artifact {
	opts, err := parseOptions(m.Parameters())
	if err != nil {
		m.AddError(err.Error())
		return m.Artifacts()
	}
	services, err := selectServices(opts.services, opts.filter, targets, pkgs)
	if err != nil {
		m.AddError(err.Error())
		return m.Artifacts()
	}

	// Filter every message, reachable or not, so each rule is checked
	// against the whole input and excluded fields drop their diagnostics.
	reg := mapping.Build(pkgs)
	fieldDiags := map[string][]mapping.Diag{}
	for _, d := range reg.Order {
		fieldDiags[d.FQN] = d.Finalize(opts.filter)
	}
	var problems []string
	for _, e := range opts.filter.Unmatched() {
		problems = append(problems, e.Error())
	}

	var diags []mapping.Diag
	var roots []string
	for _, s := range services {
		diags = append(diags, s.Diags...)
		for _, op := range s.Operations {
			op.Input.Refs(func(r string) { roots = append(roots, r) })
			op.Output.Refs(func(r string) { roots = append(roots, r) })
		}
	}

	res := closure.Walk(roots, reg.Refs)
	for _, c := range res.Cycles {
		m.Debugf("reference cycle: %s", c)
	}
	missing := make([]string, 0, len(res.Missing))
	for fqn := range res.Missing {
		missing = append(missing, fqn)
	}
	sort.Strings(missing)
	for _, fqn := range missing {
		problems = append(problems, fmt.Sprintf("internal error: %s is referenced by %v but was not mapped", fqn, res.Missing[fqn]))
	}

	var defs []*mapping.Def
	for _, d := range reg.Order {
		if res.Marked[d.FQN] {
			defs = append(defs, d)
			diags = append(diags, fieldDiags[d.FQN]...)
		}
	}

	files, layoutDiags := layout(services, defs, opts.format)
	diags = append(diags, layoutDiags...)
	if len(diags) > 0 {
		problems = append(problems, formatDiags(diags))
	}
	if len(problems) > 0 {
		m.AddError(strings.Join(problems, "\n"))
		return m.Artifacts()
	}

	for _, f := range files {
		content, err := emit.Encode(opts.format, f.header(opts.filter), f.doc())
		if err != nil {
			m.AddError(fmt.Sprintf("%s: %v", f.path, err))
			continue
		}
		m.AddGeneratorFile(f.path, string(content))
	}
	return m.Artifacts()
}

// selectServices returns the services named by the services option, or
// every service in the files to generate, ordered by full name. Every
// method in the input is checked against the filter, so a methods rule
// counts as matched even when it names an unselected service.
func selectServices(names []string, f *filter.Filter, targets map[string]pgs.File, pkgs map[string]pgs.Package) ([]*mapping.Service, error) {
	all := map[string]pgs.Service{}
	for _, p := range pkgs {
		for _, file := range p.Files() {
			for _, s := range file.Services() {
				all[strings.TrimPrefix(s.FullyQualifiedName(), ".")] = s
				for _, meth := range s.Methods() {
					f.ExcludesMethod(meth.FullyQualifiedName())
				}
			}
		}
	}
	var picked []pgs.Service
	if len(names) == 0 {
		for _, file := range targets {
			picked = append(picked, file.Services()...)
		}
	} else {
		for _, n := range names {
			s, ok := all[n]
			if !ok {
				return nil, fmt.Errorf("services: no service named %q", n)
			}
			picked = append(picked, s)
		}
	}
	if len(picked) == 0 {
		return nil, fmt.Errorf("no services to generate; the files to generate declare none and the services option is unset")
	}
	out := make([]*mapping.Service, 0, len(picked))
	seen := map[string]bool{}
	for _, s := range picked {
		ms := mapping.MapService(s, f)
		if !seen[ms.FQN] {
			seen[ms.FQN] = true
			out = append(out, ms)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].FQN < out[j].FQN })
	return out, nil
}

func formatDiags(diags []mapping.Diag) string {
	sort.SliceStable(diags, func(i, j int) bool {
		a, b := diags[i], diags[j]
		if a.File != b.File {
			return a.File < b.File
		}
		return a.Line < b.Line
	})
	var lines []string
	seen := map[string]bool{}
	for _, d := range diags {
		s := d.String()
		if !seen[s] {
			seen[s] = true
			lines = append(lines, s)
		}
	}
	return strings.Join(lines, "\n")
}

// target is where a def is written.
type target struct {
	path string
	key  string
}

// outFile is one generated document: a package's defs, plus its services if
// it declares any.
type outFile struct {
	path       string
	sources    map[string]bool
	dependency bool
	services   []*mapping.Service
	defs       []*mapping.Def
	targets    map[string]target // every emitted def, by full name
}

// layout groups the services and reachable defs into one file per package
// (D3) and assigns the $defs keys.
func layout(services []*mapping.Service, defs []*mapping.Def, format emit.Format) ([]*outFile, []mapping.Diag) {
	var diags []mapping.Diag
	byPkg := map[string]*outFile{}
	targets := map[string]target{}
	get := func(pkg string) *outFile {
		f, ok := byPkg[pkg]
		if !ok {
			f = &outFile{sources: map[string]bool{}, targets: targets}
			byPkg[pkg] = f
		}
		return f
	}
	for _, s := range services {
		f := get(s.Package)
		f.services = append(f.services, s)
		f.sources[s.File] = true
	}
	for _, d := range defs {
		f := get(d.Package)
		f.defs = append(f.defs, d)
		f.sources[d.File] = true
		f.dependency = f.dependency || d.Dependency
	}

	pkgNames := make([]string, 0, len(byPkg))
	for p := range byPkg {
		pkgNames = append(pkgNames, p)
	}
	sort.Strings(pkgNames)
	files := make([]*outFile, 0, len(pkgNames))
	for _, p := range pkgNames {
		f := byPkg[p]
		var err error
		f.path, err = naming.FilePath(p, len(f.services) > 0, format.Ext())
		if err != nil {
			diags = append(diags, mapping.Diag{File: firstSource(f.sources), Subject: p, Msg: err.Error()})
		}
		owner := map[string]*mapping.Def{}
		for _, d := range f.defs {
			key := naming.DefKey(d.Package, d.FQN)
			if other, ok := owner[key]; ok {
				at := d.At
				at.Msg = fmt.Sprintf("$defs key %q is also used by %s; rename one of them", key, other.FQN)
				diags = append(diags, at)
			}
			owner[key] = d
			targets[d.FQN] = target{path: f.path, key: key}
		}
		diags = append(diags, f.hoistInlineShapes(owner)...)
		files = append(files, f)
	}
	diags = append(diags, disambiguate(files)...)
	return files, diags
}

// flatLanguages put every type from every file into one namespace, so a
// $defs key used in two packages collides there. Java keeps a package per
// file and needs no override.
var flatLanguages = []string{"go", "py", "ts"}

// disambiguate gives every def whose key is used in more than one package
// an x-<lang>-name of its package segment plus the key, such as
// NamespaceLifecycleSpec and ProjectLifecycleSpec.
func disambiguate(files []*outFile) []mapping.Diag {
	type use struct {
		file *outFile
		def  *mapping.Def
	}
	byKey := map[string][]use{}
	for _, f := range files {
		for _, d := range f.defs {
			k := f.targets[d.FQN].key
			byKey[k] = append(byKey[k], use{f, d})
		}
	}
	var diags []mapping.Diag
	for _, f := range files {
		for _, d := range f.defs {
			key := f.targets[d.FQN].key
			if len(byKey[key]) < 2 {
				continue
			}
			seg, err := naming.Segment(d.Package)
			if err != nil {
				continue // reported by layout
			}
			name := naming.UpperFirst(seg) + key
			if len(byKey[name]) > 0 {
				at := d.At
				at.Msg = fmt.Sprintf("$defs key %q is used in several packages, and its disambiguated name %q is taken too; rename one of them", key, name)
				diags = append(diags, at)
				continue
			}
			for _, lang := range flatLanguages {
				d.Node.Extensions = append(d.Node.Extensions, schema.Extension{Key: "x-" + lang + "-name", Value: name})
			}
		}
	}
	return diags
}

// hoistInlineShapes moves an inline object property into $defs when the
// name nexgen would synthesize for it, <Model><Property>, is already a def
// key. Namespace.regionStatus (a map) would otherwise be named
// NamespaceRegionStatus, which is the message of that name. The hoisted def
// is <Model><Property>Map for a map and <Model><Property>Object otherwise.
func (f *outFile) hoistInlineShapes(owner map[string]*mapping.Def) []mapping.Diag {
	var diags []mapping.Diag
	var defs []*mapping.Def
	for _, d := range f.defs {
		defs = append(defs, d)
		key := f.targets[d.FQN].key
		for i, p := range d.Node.Properties {
			n := p.Schema
			if n.Type != "object" {
				continue
			}
			synth := key + naming.UpperFirst(p.Name)
			if owner[synth] == nil {
				continue
			}
			name := synth + "Object"
			if n.AdditionalProperties != nil || n.OpenMap {
				name = synth + "Map"
			}
			if other, ok := owner[name]; ok {
				at := d.At
				at.Msg = fmt.Sprintf("field %s needs the $defs key %q, which %s already uses; rename one of them", p.Name, name, other.FQN)
				diags = append(diags, at)
				continue
			}
			shape := *n
			shape.Deprecated, shape.Extensions = false, nil
			hoisted := &mapping.Def{FQN: d.FQN + "." + p.Name + "#shape", Package: d.Package, File: d.File, Node: &shape}
			owner[name] = hoisted
			f.targets[hoisted.FQN] = target{path: f.path, key: name}
			defs = append(defs, hoisted)
			d.Node.Properties[i].Schema = &schema.Node{Ref: hoisted.FQN, Deprecated: n.Deprecated, Extensions: n.Extensions}
		}
	}
	f.defs = defs
	return diags
}

func firstSource(sources map[string]bool) string {
	first := ""
	for s := range sources {
		if first == "" || s < first {
			first = s
		}
	}
	return first
}

func (f *outFile) header(flt *filter.Filter) []string {
	h := []string{generatedHeader}
	srcs := make([]string, 0, len(f.sources))
	for s := range f.sources {
		srcs = append(srcs, s)
	}
	sort.Strings(srcs)
	for _, s := range srcs {
		line := "source: " + s
		if f.dependency {
			line += " (from a dependency module)"
		}
		h = append(h, line)
	}
	if flt != nil {
		h = append(h, "filter: "+flt.Path)
	}
	return h
}

// ref resolves a def's full name to a $ref from this file: local
// "#/$defs/<Key>", or a path relative to this file's directory.
func (f *outFile) ref(fqn string) string {
	t, ok := f.targets[fqn]
	if !ok {
		// The closure marks every referenced def, so this is a bug.
		panic(fmt.Sprintf("nexgen: %s has no def", fqn))
	}
	if t.path == f.path {
		return "#/$defs/" + t.key
	}
	return relPath(path.Dir(f.path), t.path) + "#/$defs/" + t.key
}

// relPath is target relative to dir; both are slash-separated and relative
// to the output root.
func relPath(dir, target string) string {
	from := strings.Split(dir, "/")
	to := strings.Split(target, "/")
	i := 0
	for i < len(from) && i < len(to)-1 && from[i] == to[i] {
		i++
	}
	parts := make([]string, 0, len(from)-i+len(to)-i)
	for range from[i:] {
		parts = append(parts, "..")
	}
	return strings.Join(append(parts, to[i:]...), "/")
}

func (f *outFile) doc() *emit.Map {
	doc := &emit.Map{}
	if len(f.services) > 0 {
		doc.Set("nexusrpc", emit.Quoted(nexusrpcVersion))
	}
	doc.Set("$schema", schemaURI)
	if len(f.services) > 0 {
		svcs := &emit.Map{}
		for _, s := range f.services {
			svc := &emit.Map{}
			if s.Description != "" {
				svc.Set("description", s.Description)
			}
			if s.Deprecated {
				svc.Set("deprecated", true)
			}
			svc.Set("fqn", s.FQN)
			ops := &emit.Map{}
			for _, op := range s.Operations {
				o := &emit.Map{}
				if op.Description != "" {
					o.Set("description", op.Description)
				}
				if op.Deprecated {
					o.Set("deprecated", true)
				}
				o.Set("fqn", op.Wire)
				o.Set("input", op.Input.Doc(f.ref))
				o.Set("output", op.Output.Doc(f.ref))
				for _, ov := range op.Overrides {
					o.Set(ov.Key, ov.Name)
				}
				ops.Set(op.Key, o)
			}
			svc.Set("operations", ops)
			svcs.Set(s.Name, svc)
		}
		doc.Set("services", svcs)
	}
	defs := &emit.Map{}
	for _, d := range f.defs {
		defs.Set(f.targets[d.FQN].key, d.Node.Doc(f.ref))
	}
	doc.Set("$defs", defs)
	return doc
}
